name = "UnicodeMath"
uuid = "0d34d933-8ee7-410a-b7f5-1fe550df0327"
authors = ["Manuel B. Berkemeier <mmanberk@protonmail.com>"]
version = "0.0.1-DEV"

[deps]
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
UnPack = "1.0.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[targets]
test = ["Test", "UnPack"]
